<?php

/**
* @file
 * Filter duplicate and other unwanted clicks from ad statistics.
 *
 * Copyright (c) 2005-2009.
 *   Jeremy Andrews <jeremy@tag1consulting.com>.
 */

/**
 * TODO:
 *  - Filter out bots and spiders using user_agent field.
 *  - Add administrative ability to enter IP or range to filter.
 */

if (!defined('AD2_CLICK_NEW')) {
  define('AD2_CLICK_NEW', 0);
  define('AD2_CLICK_VALID', 1);
  define('AD2_CLICK_DUPLICATE', 2);
  define('AD2_CLICK_OWNER', 3);
  define('AD2_CLICK_FILTER_ROLE', 4);
  define('AD2_CLICK_BOT', 5);
}
/**
 * Provide text version for statistics output.
 */
function ad2_filter_status_text($status) {
  $output = '<div class="click-status">';
  switch ($status) {
    case 0:
      $output .= '<div class="click-new">'. t('New') .'</div>';
      break;
    case 1:
      $output .= '<div class="click-valid">'. t('Valid') .'</div>';
      break;
    case 2:
      $output .= '<div class="click-duplicate">'. t('Duplicate') .'</div>';
      break;
    case 3:
      $output .= '<div class="click-owner">'. t('Ad owner') .'</div>';
      break;
    case 4:
      $output .= '<div class="click-filtered-role">'. t('Filtered role') .'</div>';
      break;
    case 5:
      $output .= '<div class="click-bot">'. t('Bot') .'</div>';
      break;
    default:
      $output .= '<div class="click-unknown">'. t('Unknown') .'</div>';
      break;
  }
  $output .= '</div>';
  return $output;
}

/**
 * Perform on-the-fly click filtering.
 */
function ad2_filter_status($aid, $hostid) {
  global $user;
  //return CLICK_VALID;
  if (user_access('ad2 filter clicks')) {
    return AD2_CLICK_FILTER_ROLE;
  }
  if (preg_match('/bot|crawl|spider/i', $_SERVER['HTTP_USER_AGENT'])) {
    return AD2_CLICK_BOT;
  }
  // See if the click came from an owner of the ad.
  // if (module_exists('ad_owners')) {
    // $result = db_query('SELECT oid FROM {ad_owners} WHERE aid = %d AND uid = %d', $aid, $user->uid);
    // if (db_result($result)) {
      // return CLICK_OWNER;
    // }
  // }
  // See if the click came from a duplicate uid or ip address.
  if ($user->uid) {
    $result = db_query(
    	"SELECT cid FROM ad_clicks 
    	WHERE aid = :aid 
    	AND status = :status 
    	AND (uid = :uid OR hostname = :host) 
    	and timestamp > :timestamp", 
    	array(
    		':aid' => $aid, 
    		':status' => AD2_CLICK_VALID , 
    		':uid' => $user->uid , 
    		':host' =>  ip_address() , 
    		':timestamp' => time() - 3*60*60 
		));
  }
  else {
    $result = db_query(
    	"SELECT cid FROM ad_clicks 
    	WHERE aid = :aid 
    	AND status = :status 
    	AND hostname = :host 
    	and timestamp > :timestamp",  
    	array(
    		':aid' => $aid, 
    		':status' => AD2_CLICK_VALID ,  
    		':host' =>  ip_address() , 
    		':timestamp' => time() - 3*60*60  
		));
  }
  //tr( get_class_methods($result) );
  //die();
  
  //tr( $result->rowCount() );
  if ( $result->rowCount() ) {
    return AD2_CLICK_DUPLICATE;
  }
  return AD2_CLICK_VALID;
}


function ad2_filter_permission() {
  return array(
    'ad2 view filtered clicks' => array(
      'title' => t('view filtered clicks'), 
      'description' => t('view filtered clicks.'),
    ),
   'ad2 filter clicks' => array(
      'title' => t('filter clicks'), 
      'description' => t('filter clicks.'),
    ),
  );
}

