<?
// 
// function ad2_parent_config_form(&$form , &$form_state ){
// 	
// 	
	// $types = node_type_get_names();
// 	
	// $form['type'] = array(
		// '#title' => 'chosse parent node type',
		// '#type' => 'checkboxes',
		// '#options' => $types,
		// '#default_value' => variable_get( 'ad2_parent_node_types' , array() ),
	// );
// 	
	// $form['submit'] = array(
		// '#type' => 'submit',
		// '#value' => t('Save'),
	// );
// 	
	// return $form;
// }
// 
// function ad2_parent_config_form_submit(&$form , &$form_state ){
// 		
	// $types = array_keys( array_filter( $form_state['values']['type'] )  );
	// variable_set('ad2_parent_node_types' , $types );
	// drupal_set_message('Data saved');
// }
