<?

function ad2_bycat_ad2_score_component_info(){
	return array(
		'bycat' => 'רלוונטיות הקטגוריה',
	);
}


function ad2_bycat_ad2_cron_info(){
	$jobs['default']['info'] = 'bycat score component';
	return $jobs;
}

function ad2_bycat_ad2_cron_run($delta){
	
	
	$last = variable_get("ad2_bycat_default_last_ad2_cron_run" , 0 );
	
	if( REQUEST_TIME > $last + 7*24*60*60 ){
	
		// $q = db_select('ads' , 'a');
		// $q->fields('a' , array('aid' , 'nid'));
// 		
		// $rows = $q->execute()->fetchAll();
		// $ads = array();
		// foreach ($rows as $row) {
			// $ads[$row->nid][] = $row->aid;
		// }
		
		$q = db_select('ad2_rank' , 'a');
		$q->fields('a' , array('aid' , 'nid'));
		
		$rows = $q->execute()->fetchAll();
		$ads = array();
		foreach ($rows as $row) {
			if( ! isset($ads[$row->nid]) ){
				$ads[$row->nid] = array();
			}
			if( ! in_array($row->aid , $ads[$row->nid])){
				$ads[$row->nid][] = $row->aid;
			}
		}
	
		
		$relevancy = array();
		$r = db_query("select * from cat_relevancy")->fetchAll();
		foreach ($r as $row ) {
			$relevancy[$row->nid][$row->tid] = $row;
		}
		
		foreach ($relevancy as $nid => $values ) {
			foreach ($values as $tid => $row) {
				$score = round( 1 + ( ($row->relevancy - 5 ) / 10 ) , 4 );
				
				
				if( ! isset($ads[$nid]))
					continue;
				
				db_update('ad2_rank')
					->condition('aid' , $ads[$nid] , 'IN')
					->condition('tid' , $tid)
					->fields(array(
						'comp_bycat' => $score,
						'rerank' => 1,
					))
					->execute()
					;
			}
		}
		
		variable_set("ad2_bycat_default_last_ad2_cron_run" , REQUEST_TIME );
	
	}
}